/**
 * ghostscript/pdfx.ts — the optional PDF/X-3 leg (SPEC §9 step 9b).
 *
 * Lulu and Gelato accept sRGB and convert themselves; a Turkish printer may demand PDF/X.
 * Ghostscript is the only tool in the stack that can produce it, and it only produces X-3
 * (X-1a cannot be generated by gs — the SPEC note is correct). TR printers accept X-1a:2001
 * OR X-3, so X-3 is enough.
 *
 * Two flags matter more than the rest:
 *   · `-dDeviceGrayToK=true` — without it, black text is rebuilt from four inks and any
 *     registration drift on the press makes it look doubled.
 *   · `-dPDFXTrimBoxToMediaBoxOffset` — gs recomputes the TrimBox from the MediaBox; the
 *     offset is the bleed, in points, on each side.
 *
 * The binary is not bundled and is usually absent in CI, so this module is built to be
 * TESTED WITHOUT IT: `buildGhostscriptArgs` is pure and asserted in the unit tests, and
 * `convertToPdfX3` only shells out when a path is configured.
 */

import { spawn } from 'node:child_process';

import { mmToPt } from '../units';
import type { BookFormatSpec } from '../formats';

export interface PdfX3Options {
  /** Absolute path to `gs`. From `packages/config` → `PDF_GHOSTSCRIPT_PATH`. */
  ghostscriptPath: string;
  /** ISO Coated v2 (ECI) or whatever the printer names. */
  iccProfilePath: string;
  /** `PDFX_def.ps` prologue that names the output intent. */
  pdfxDefPath: string;
  inputPath: string;
  outputPath: string;
  bleedMm: number;
  timeoutMs?: number;
}

export function buildGhostscriptArgs(options: PdfX3Options): string[] {
  const offset = mmToPt(options.bleedMm).toFixed(2);
  return [
    '-dPDFX',
    '-dBATCH',
    '-dNOPAUSE',
    '-dSAFER',
    '-sDEVICE=pdfwrite',
    '-sColorConversionStrategy=CMYK',
    '-dProcessColorModel=/DeviceCMYK',
    '-dOverrideICC=true',
    `-sOutputICCProfile=${options.iccProfilePath}`,
    // Black text must stay single-ink. This flag is the whole reason the file exists.
    '-dDeviceGrayToK=true',
    `-dPDFXTrimBoxToMediaBoxOffset=[${offset} ${offset} ${offset} ${offset}]`,
    `-sOutputFile=${options.outputPath}`,
    options.pdfxDefPath,
    options.inputPath,
  ];
}

export function pdfX3OptionsForFormat(
  format: BookFormatSpec,
  paths: Omit<PdfX3Options, 'bleedMm'>,
): PdfX3Options {
  return { ...paths, bleedMm: format.bleedMm };
}

export class GhostscriptError extends Error {
  constructor(
    message: string,
    readonly code: number | null,
    readonly stderr: string,
  ) {
    super(message);
    this.name = 'GhostscriptError';
  }
}

/** Runs gs. Rejects with `GhostscriptError` — never a silent half-converted file. */
export async function convertToPdfX3(options: PdfX3Options): Promise<void> {
  const args = buildGhostscriptArgs(options);
  await new Promise<void>((resolve, reject) => {
    const child = spawn(options.ghostscriptPath, args, { stdio: ['ignore', 'ignore', 'pipe'] });
    let stderr = '';
    const timer = setTimeout(() => child.kill('SIGKILL'), options.timeoutMs ?? 120_000);

    child.stderr?.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on('error', (error) => {
      clearTimeout(timer);
      reject(new GhostscriptError(`ghostscript could not start: ${error.message}`, null, stderr));
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      if (code === 0) resolve();
      else reject(new GhostscriptError(`ghostscript exited with ${code}`, code, stderr));
    });
  });
}
